### ISSUE TITLE
QBDI can not instrument MacOS's library

### ISSUE THREAD

**Issue by sleicasper** [QBDI/QBDI#124]
`addInstrumentedModuleFromAddr` and `addInstrumentedRange` don't work with any `dylib` on macos.

**Comment by nsurbay** [comment]
Can you be a bit more precise ?

- Do you use QBDIPreload or not ?
- Do you run QBDI with a start address of the library or of a binary ?
- If you run QBDI on a binary, is the library called directly by the binary (no jump to the loader or another no instrumented library) ? 
- Is the library executed between the event ``EXEC_TRANSFER_CALL``and ``EXEC_TRANSFER_RETURN`` ?
- Does macOS have a flag like ``LD_BIND_NOW`` ?
- Can you post a minimized code that reproduce the bug ?

**Comment by nsurbay** [comment]
The problem may be related to the ``ExecBroker`` and the limitation of the instrumented range (see https://qbdi.readthedocs.io/en/stable/api_cpp.html#execution-filtering)

**Comment by sleicasper** [comment]
I used a hand made library which call system's library function. Inside QBDI, I run from function in hand made library, and instrumented library is system's library.

**Comment by nsurbay** [comment]
When you call the first time an external method, the execution may call the linker instead of the expected library to resolv the address of the called method.

Can you try to run the program with the environment variable ``DYLD_BIND_AT_LAUNCH=YES`` ? (see https://www.unix.com/man-page/mojave/1/dyld)

In addition, can you hook the event ``EXEC_TRANSFER_CALL`` and resolve the next instruction address. If QBDI doesn't instrument a module, it is likely that the execution goes out of the instrumented range. The event ``EXEC_TRANSFER_CALL`` is trigger before the switch to real execution.

**Comment by sleicasper** [comment]
yeah, you are right, control flow transferred into un-instrumented region first, because it call functions like `objc_msgSend` and `objc_alloc`. I think it is related to objective-c 's message passing mechanism?
