### ISSUE TITLE
Status of this project

### ISSUE THREAD

**Issue by 0xchase** [QBDI/QBDI#143]
I'm trying to decide on a DBI framework to support a project I'm working on. QBDI seems ideally suited to my use case, especially with the Frida integration and simple API. 

However, it seems like development has been slow the past year or so, especially compared to other frameworks. Are there long term plans for future development? I'm trying to decide if building a tool on this project is a good decision long term, or if I should just go with Pin/Dynamorio.

**Comment by nsurbay** [comment]
Hello,

The project is maintained but the new feature are merged in ``master`` at each release. You can take a look to the branch ``dev-next`` to have a better overview of the current development.

However, the ARM support will be drop with the next release. It hasn't be tested since the release ``0.6.2`` and seems to not compile with the current release.

**Comment by 0xchase** [comment]
Ok thanks
