### ISSUE TITLE
Android Frida-QBDI installation process problem

### ISSUE THREAD

**Issue by Rainker93** [QBDI/QBDI#223]
**Bug description**

First script
```
const qbdi = require('/usr/local/share/qbdi/frida-qbdi'); // import QBDI bindings
qbdi.import(); // set bindings to the global environment

var vm = new QBDI();
console.log("QBDI version is " + vm.version.string);
```

```
ReferenceError: 'require' is not defined at <anonymous> (MyScript.js:1)
```

Second script

```
var vm = new QBDI();
console.log("QBDI version is " + vm.version.string);
```

```
ReferenceError: 'QBDI' is not definedat <anonymous> (MyScript.js:2)
```

**Specific command to reproduce the bug**

frida-compile command:  ```frida-compile MyScript.js -o MyScriptCompiled.js```

frida command: ``` frida -Uf [Package Name] -l MyScriptCompiled.js ```

**Version (please complete the following information):**
- OS: Kali(Debian 10, X64), Mobile(Android8, ARM64)
- QBDI version (returned by getVersion) and commit hash (if not a release version)
- Frida version: 15.2.0
- Python version: Python 3

**Additional context**

Hi, I don't know if you remember, but I had emailed you before.

I downgraded the frida version as you suggested.(15.2.0)

However, frida-qbdi is still not running.

All my settings are as follows:

**[PC(Kali)]**

**Install Frida**
pip install frida-tools -----> OK (version: 15.2.0)

**Install frida-compile and add the binary directory to your PATH env variable**
npm install frida-compile babelify
export PATH=$PATH:$(pwd)/node_modules/.bin ----->  OK 

**Install QBDI-releases**
(My guess is that something is wrong here.)

URL: https://github.com/QBDI/QBDI/releases
Download: QBDI-0.8.0-debian10-X86.deb
dpkg -i QBDI-0.8.0-debian10-X86_64.deb

**[Mobile(Android8, ARM64)]**

URL: https://qbdi.quarkslab.com/
	Android(0.9.0) 
	- Download: Android (x86-64)
	- Decompression: urs -> local -> lib -> libQBDI.so(Moved this file to mobile.)
	- My device(Android) -> /data/local/tmp/ -> chmod 777 libQBDI.so

As you can see, this is my environment.

Can you tell me where in my environment is wrong?

My goal is to analyze native library in mobile application.

Could you please help me?

**Comment by nsurbay** [comment]
Hello,

As mention in the previous mail, frida change the syntax of the module file in the version 15.2. You need to downgrade to a version __before__ 15.2 (like 15.1.28) to use the current `frida-qbdi.js` script.

Also, as your mobile runs on arm64, the version x86-64 (or amd64) of QBDI will not work. You need to use an arm64 version of QBDI. We just begin to support this architecture (#222), but no release is available yet. Therefore, you can either :
- Compile the library directly
- Use the package generated with Github Action (https://github.com/QBDI/QBDI/actions/workflows/android.yml)

Finally, as the API of QBDI have some change between 0.8.0 and 0.9.0, you may get an error for compiling your script against `frida-qbdi.js` 0.8.0 and run the script with the version 0.9.0 of QBDI. Moreever, the version 0.8.0 doesn't support the ARM architecture (both armv7 and aarch64) ([see code](https://github.com/QBDI/QBDI/blob/e419cc0a840a524bf69c3948e91239aa997d25e8/tools/frida-qbdi.js#L336url)). In order to use the good version of `frida-qbdi.js`:
- Download or compile a version of QBDI for android AARCH64
- extract the library libQBDI.so and upload it on your device
- extract the `frida-qbdi.js` to a directory in your PC and change the first line of you script to 
```
const qbdi = require('/<my_directory>/frida-qbdi');
qbdi.import(); 
```

**Comment by Rainker93** [comment]
hello,

I still get the error in the require statement.

I have sent you my entire process as a PPT by e-mail, can you please check it?

I'm really sorry for sending you an email.

Thank you!!!

**Comment by nsurbay** [comment]
I received you mail but I think it's more helpful for the others users of QBDI if you avoid to use mails for support and use this issue to describe your problem. Others people with the same problem can find this issue later and resolve the problem themself. Moreover, I'm not the only developer nor the best user of QBDI for mobile application. A more appropriate response might come from another user reading this ticket.

I will resume your issue in two points:
1. Frida has change his API (and how we need to include/compile frida-qbdi.js)
2. You want an example of how to use frida-QBDI out of the box on an android device.

As I need to update the Frida-QBDI API to work with the latest version of Frida, I prefer to finish to support the last version of frida instead of trying to debug your settings, that will break as soon as you update. I will update this issue when I finish the support of the last version.

However, if you still want to use the current state of Frida-QBDI, I think the problem can be the version frida-compile. You can try the followed command:
```
npm install frida-compile@10.2.5 babelify
./node_modules/.bin/frida-compile MyScript.js -o MyScriptCompiled.js
```

**Comment by nsurbay** [comment]
I finish to work with the new frida-QBDI API. I test it against a linux x86_64 binary, but i cannot test it against an android aarch64 apps (I don't have a rooted android device to test it). Note that AARCH64 is still a recent support and some bug should be expected.

To work with the new API, frida should be update to a version greater than 15.2 (like the current 16.0.2) both on the phone and the PC.
```bash
pip install --upgrade --user 'frida>=15.2' frida-tools
```

The new version of API needs some change in the user script :
- the object `QBDI` has been renamed `VM`. Any line with ```new QBDI()``` should be replace with ```new VM()```
- The `frida-qbdi.js` should now be on the same directory as the user script
- The inclusion of `frida-qbdi.js` will now used the `include` keyword:
```patch
-const qbdi = require('/usr/local/share/qbdi/frida-qbdi'); // import QBDI bindings
-qbdi.import(); // set bindings to the global environment
+import { VM, InstPosition, VMAction } from "./frida-qbdi.js";
```

You will need to use the last commit of the branch `support_arm` (or the artefact of [this action](https://github.com/QBDI/QBDI/actions/runs/3436319716)). In a new directory with only your script and QBDI archive, you should be able to compile your script with the followed command :

```bash
$ ls
QBDI-0.9.1-devel-android-AARCH64.tar.gz  script.js
$ mkdir extract
$ tar xf QBDI-0.9.1-devel-android-AARCH64.tar.gz -C extract 
$ find extract -name frida-qbdi.js -exec ln -s {} . \;
$ find extract -name libQBDI.so -exec ln -s {} . \;
$ ls -lh
total 8,8M
drwxr-xr-- 3 user user   60 10 nov.  17:32 extract
lrwxrwxrwx 1 user user   49 10 nov.  17:32 frida-qbdi.js -> extract/usr/local/share/qbdiAARCH64/frida-qbdi.js
lrwxrwxrwx 1 user user   32 10 nov.  17:32 libQBDI.so -> extract/usr/local/lib/libQBDI.so
-rw-r--r-- 1 user user 8,8M 10 nov.  11:21 QBDI-0.9.1-devel-android-AARCH64.tar.gz
-rw-r--r-- 1 user user 4,3K 10 nov.  17:33 script.js
$ adb push libQBDI.so /data/local/tmp
libQBDI.so: 1 file pushed, 0 skipped. 35.3 MB/s (6181248 bytes in 0.167s)
$ adb shell chmod 777 /data/local/tmp/libQBDI.so 
$ npm install frida-compile babelify 
...
$ cat package.json| grep frida-compile
    "frida-compile": "^16.1.3"
$ ./node_modules/.bin/frida-compile script.js -o scriptCompiled.js
$ frida -Uf com.app.example -l scriptCompiled.js
```

The documentation for the branch `support_arm` is available in preview [here](https://qbdi.readthedocs.io/en/support_arm/index.html). As android application have Java code, that isn't supported by QBDI, you may take a look to [this blogpost](https://blog.quarkslab.com/why-are-frida-and-qbdi-a-great-blend-on-android.html) in order to intercept the call of native method.

**Comment by nsurbay** [comment]
QBDI 0.10.0 has been release with the support of AARCH64 and the support of frida.
If you have any new issue, feel free to open an new issue.
