### ISSUE TITLE
[question] support for multithreading

### ISSUE THREAD

**Issue by luickk** [QBDI/QBDI#232]
Hi,
I'm planning to use qbdi for analysing a multithreading heavy app. I've been playing around a bit with the framework and tried to find out wether reading memory access information would work but am still unsure about the whole situation. In the docs multithreading is not supported but in another [issue](https://github.com/QBDI/QBDI/issues/204#issuecomment-1047097258) I've also read that upon creating a thread one would have to reinstantiate the vm again. Is that a viable option? I'm really only interested in the threads memory activity...
best regards Luick

**Comment by nsurbay** [comment]
Hello,

QBDI itself doesn't support multithreading, but it's mainly because we support many OS, and multithreading API is different for each of them. For example, QBDI isn't able to detect a call to `pthread_create` on Linux and to propagate the instrumentation to the new thread.

I'm never tried to instrument multithreading binary, but the core of QBDI doesn't use any global variable, so each instance of the VM is independent of each other. Each instance of the VM has it one instance of the LLVM disassembler and assembler but the first created VM will also initialise some LLVM structure. I would therefore recommend initialising the first VM without concurrency.

Once you detect a creation of a new thread, you can either :
- Create a VM in the main thread and manually switch the execution between the main VM and the thread VM;
- Create a VM in the main thread, then create a thread that will run this VM;
- Create a thread that will create a VM and instrument the original thread code;

For the case, you should manually allocate a stack for the instrumented thread method, as the VM will use either the main thread stack or the new thread stack.

I'm confident that QBDI can be multithreading, however, I'm more concerned about the side effects of some exclusive and atomic store instructions inside the instrumented code. For example, in AARCH64 and ARM architecture, the instructions ``LDREX`` and ``STREX`` allow creating an atomic store operation. But if you add some instrumentation between these two instructions, the local/exclusive monitor can be clear, which may create an infinite loop. To support this instruction in monothread, we implement our one local monitor that is restored before the ``STREX``. However, this mechanism will not work in a multithreading application, where ``STREX`` can be used to create a mutex or a semaphore.

My main concern is that QBDI may break some mutex and semaphore mechanism when instruments multithreading code. If all the mutex and semaphores are handled with an external library (like ``libpthread``), I would recommend to not instrument the library. Otherwise, it should be safest to run only one VM at a time, and manually switch the execution between  multiple VMs.
