### ISSUE TITLE
_JNIEnv::GetMethodID Error: abort was called 

### ISSUE THREAD

**Issue by imethod** [QBDI/QBDI#242]
**Bug description**
An error occurred when qbdi called the env function

**Bug log**
![image](https://github.com/QBDI/QBDI/assets/109936536/7ddbb7cb-e8c6-45dc-bdf2-f13c2558d50f)
![image](https://github.com/QBDI/QBDI/assets/109936536/84174f08-82bd-4b09-9988-7a6fec5f52a4)

Also, I want to know how to get qbdi to ignore some code 
Like an inline one memcpy ,It's very time-consuming
Or ignore the trace of a child function, In order to concentrate on the function of analysis

**Comment by imethod** [comment]
I used "vm.addInstrumentedModule("libart.so")" and the problem seemed to be solved 

But I don't want to trace libart in detail
So is there any way to ignore some instructions or function calls

**Comment by nsurbay** [comment]
Hello,

QBDI has a really simple model to select which region to instrument :  "Instrumentation range". Before starting QBDI, you must select which region of code must be instrumented by QBDI, or run natively (without QBDI). When a code run inside QBDI, QBDI should never ''lost'' the control of the instrumented program. However, when the code run without QBDI, we have no control of his execution.

When you start the VM, the first address must be within the Instrumentation range. QBDI will instrument the basicblock (consecutive instruction without jmp/call/ret) and execute it. At the end of the execution of the basic block, QBDI will verify if the next address is within the Instrumentation range or not. In the first case, it will begin the same loop, until the execution stop, or the address is outside of the instrumentation range.

When the next address is outside of the instrumentation range, QBDI will try to transfer the execution to native execution. Currently, only one method exist for this : QBDI searchs a return address (in LR or on the first element on the stack) and verify if this address is within the instrumentation range. In this case, the return address is replaced by a special address and the execution continue outside of QBDI. During this "native" execution, QBDI has no control of the execution. The execution may execute range of code inside the instrumentation range, but we have no method to detect that. QBDI catches back the execution when the code uses the modified return address. This mechanism is internally called ``ExecBroker``.

This mechanism work well in most case, but have a lot of limitations. It fails to detect the execution of range within the instrumentation range during native execution, it can't handle case of exception (setjmp/longjmp, C++ exception, ...), ....

In your first message, the execution should be transfer to another library. You can verify that by checking the VM Event ``EXEC_TRANSFER_CALL``. I expect that the method doesn't return by using the modified return address set by QBDI.

> Also, I want to know how to get qbdi to ignore some code
> Like an inline one memcpy ,It's very time-consuming
> Or ignore the trace of a child function, In order to concentrate on the function of analysis

You can exclude some functions from the Instrumentation range. QBDI will use the ExecBroker to execute these method. However, you will lost the trace of this function, and any child function call by this function during his execution. In order to do that, using ``removeInstrumentedRange(fAddr, fAddr + 4)`` should do the work. However, this should not be used to skip some instructions inside a function.

You can also choose to instrument range of code, but without tracing each instruction. For this, you may :
- testing at the beginning of your callback if the instruction should not be traced, or
- replacing [addCodeCB](https://qbdi.readthedocs.io/en/stable/api_js.html#VM.addCodeCB) by many [addCodeRangeCB](https://qbdi.readthedocs.io/en/stable/api_js.html#VM.addCodeRangeCB) on each range that you want to trace.

> When I looked at the androidstudio logs I found that

The mechanism to detect the stack overflow in android is incompatible with QBDI. More specifically, I suspects that the android runtime stores the stack lower address in an internal variable, and regulary check (when you call some of his method) that the current SP is greater that this minimal address. However, when you intercept the call with frida, the real stack is used by frida, and by the QBDI engine. You allocate a second stack with ``allocateVirtualStack`` where the instrumented code (and any native execution using the ExecBroker) will run. However, this allocation is performed with ``mmap`` and may be at a lower address that the native stack. As it, you execute your code and call the android runtime with a stack address that is lower that the expected stack overflow address, which generate this exception.
I don't have an out-of-the-box solution for this problem. You may can try to replace ``allocateVirtualStack`` with a custom allocator that will allocate a memory region with greater address than the current stack. You can also try to identify how android detects a stack overflow and patchs /disable it.

**Comment by imethod** [comment]
> You can also try to identify how android detects a stack overflow and patchs /disable it.
I looked at the code for android 10 
http://aospxref.com/android-10.0.0_r47/xref/art/runtime/thread.cc#FixStackSize
Found that there is indeed this stack detection 
Unfortunately, libart is initialized when the program is running
I didn't have a chance to change these Settings
Can you introduce the implementation process of "eplace allocateVirtualStack"

**Comment by nsurbay** [comment]
I take a small look to art code. The exception may be throw by the method ``ThrowStackOverflowError``. 
I found many usage of this method like [here](https://android.googlesource.com/platform/art/+/refs/tags/android-10.0.0_r47/runtime/reflection.cc#527) or [here](https://android.googlesource.com/platform/art/+/refs/tags/android-10.0.0_r47/runtime/interpreter/interpreter.cc#407). In both case, there are a comparison between ``__builtin_frame_address(0)`` (most likely the current SP) and the result of the method [GetStackEndForInterpreter](https://android.googlesource.com/platform/art/+/refs/tags/android-10.0.0_r47/runtime/thread-inl.h#397) or [GetStackEnd](https://android.googlesource.com/platform/art/+/refs/tags/android-10.0.0_r47/runtime/thread.h#811). In both case, the result depend of ``tlsPtr_.stack_end``.
For ``JNIEnv``, you should be able to retrieve a pointer to the current ``Thread`` class (like [here](https://android.googlesource.com/platform/art/+/refs/tags/android-10.0.0_r47/runtime/jni/check_jni.cc#1308)). From the ``Thread`` pointer, you can access to ``tlsPtr_`` as a private member. You can therefore, with an analysis of a version of android, extract the needed offset and patch ``tlsPtr_.stack_end`` before executing your code in another stack. If you choose this solution, don't forget to restore the original value when you finish the execution of the newer stack.

If you want to replace ``allocateVirtualStack`` by a new allocator, you need to reproduce a similar behavior of [allocateVirtualStack](https://github.com/QBDI/QBDI/blob/dev-next/src/Utility/Memory.cpp#L77), but with another method for [alignedAlloc](https://github.com/QBDI/QBDI/blob/dev-next/src/Utility/Memory.cpp#L50). The current implementation use ``posix_memalign`` that returns an arbitrary memory region. You need instead to return a memory region with a greater address than the main stack. For this, you should use iterate on the current allocated region in order to determine an compatible address for your new stack, then call ``mmap`` with ``MAP_FIXED`` to force the allocation of this region specifically. Note that I not sure that a memory region with a greater that the stack is always available.

I have another potential solution, but it will be ever more complicate to implement. Instead of leaving the QBDI engine runs on the main stack and the instrumented code on the new allocated stack, you can perform a stack switch to run the QBDI engine on the new allocated stack, and the instrumented code on the main stack. However, this operation needs to write assembly code and can be difficult to debug. For this solution, I may implement a new API in QBDI to perform this switch.

**Comment by imethod** [comment]
> I take a small look to art code. The exception may be throw by the method `ThrowStackOverflowError`. I found many usage of this method like [here](https://android.googlesource.com/platform/art/+/refs/tags/android-10.0.0_r47/runtime/reflection.cc#527) or [here](https://android.googlesource.com/platform/art/+/refs/tags/android-10.0.0_r47/runtime/interpreter/interpreter.cc#407). In both case, there are a comparison between `__builtin_frame_address(0)` (most likely the current SP) and the result of the method [GetStackEndForInterpreter](https://android.googlesource.com/platform/art/+/refs/tags/android-10.0.0_r47/runtime/thread-inl.h#397) or [GetStackEnd](https://android.googlesource.com/platform/art/+/refs/tags/android-10.0.0_r47/runtime/thread.h#811). In both case, the result depend of `tlsPtr_.stack_end`. For `JNIEnv`, you should be able to retrieve a pointer to the current `Thread` class (like [here](https://android.googlesource.com/platform/art/+/refs/tags/android-10.0.0_r47/runtime/jni/check_jni.cc#1308)). From the `Thread` pointer, you can access to `tlsPtr_` as a private member. You can therefore, with an analysis of a version of android, extract the needed offset and patch `tlsPtr_.stack_end` before executing your code in another stack. If you choose this solution, don't forget to restore the original value when you finish the execution of the newer stack.
> 
> If you want to replace `allocateVirtualStack` by a new allocator, you need to reproduce a similar behavior of [allocateVirtualStack](https://github.com/QBDI/QBDI/blob/dev-next/src/Utility/Memory.cpp#L77), but with another method for [alignedAlloc](https://github.com/QBDI/QBDI/blob/dev-next/src/Utility/Memory.cpp#L50). The current implementation use `posix_memalign` that returns an arbitrary memory region. You need instead to return a memory region with a greater address than the main stack. For this, you should use iterate on the current allocated region in order to determine an compatible address for your new stack, then call `mmap` with `MAP_FIXED` to force the allocation of this region specifically. Note that I not sure that a memory region with a greater that the stack is always available.
> 
> I have another potential solution, but it will be ever more complicate to implement. Instead of leaving the QBDI engine runs on the main stack and the instrumented code on the new allocated stack, you can perform a stack switch to run the QBDI engine on the new allocated stack, and the instrumented code on the main stack. However, this operation needs to write assembly code and can be difficult to debug. For this solution, I may implement a new API in QBDI to perform this switch.

ok, I solved jni， according to your first solution ，no longer throwing exceptions and everything works fine
The first solution requires a version adaptation but everyone's test machine should not be easily modified
All of the above solutions should be effective

**Comment by BestToYou** [comment]
The first solution requires a version adaptation but everyone's test machine should not be easily modified

I would like to know how to specifically modify the Android source code. Please advise me

**Comment by BestToYou** [comment]
> I take a small look to art code. The exception may be throw by the method `ThrowStackOverflowError`. I found many usage of this method like [here](https://android.googlesource.com/platform/art/+/refs/tags/android-10.0.0_r47/runtime/reflection.cc#527) or [here](https://android.googlesource.com/platform/art/+/refs/tags/android-10.0.0_r47/runtime/interpreter/interpreter.cc#407). In both case, there are a comparison between `__builtin_frame_address(0)` (most likely the current SP) and the result of the method [GetStackEndForInterpreter](https://android.googlesource.com/platform/art/+/refs/tags/android-10.0.0_r47/runtime/thread-inl.h#397) or [GetStackEnd](https://android.googlesource.com/platform/art/+/refs/tags/android-10.0.0_r47/runtime/thread.h#811). In both case, the result depend of `tlsPtr_.stack_end`. For `JNIEnv`, you should be able to retrieve a pointer to the current `Thread` class (like [here](https://android.googlesource.com/platform/art/+/refs/tags/android-10.0.0_r47/runtime/jni/check_jni.cc#1308)). From the `Thread` pointer, you can access to `tlsPtr_` as a private member. You can therefore, with an analysis of a version of android, extract the needed offset and patch `tlsPtr_.stack_end` before executing your code in another stack. If you choose this solution, don't forget to restore the original value when you finish the execution of the newer stack.
> 
> If you want to replace `allocateVirtualStack` by a new allocator, you need to reproduce a similar behavior of [allocateVirtualStack](https://github.com/QBDI/QBDI/blob/dev-next/src/Utility/Memory.cpp#L77), but with another method for [alignedAlloc](https://github.com/QBDI/QBDI/blob/dev-next/src/Utility/Memory.cpp#L50). The current implementation use `posix_memalign` that returns an arbitrary memory region. You need instead to return a memory region with a greater address than the main stack. For this, you should use iterate on the current allocated region in order to determine an compatible address for your new stack, then call `mmap` with `MAP_FIXED` to force the allocation of this region specifically. Note that I not sure that a memory region with a greater that the stack is always available.
> 
> I have another potential solution, but it will be ever more complicate to implement. Instead of leaving the QBDI engine runs on the main stack and the instrumented code on the new allocated stack, you can perform a stack switch to run the QBDI engine on the new allocated stack, and the instrumented code on the main stack. However, this operation needs to write assembly code and can be difficult to debug. For this solution, I may implement a new API in QBDI to perform this switch.


I have also encountered this issue and look forward to the developer's early launch of this API for switching between main and sub threads. Thank you very much
