### ISSUE TITLE
undefined reference to `qbdi_getInstAnalysis'

### ISSUE THREAD

**Issue by Gavin0210** [QBDI/QBDI#250]
I install the qbdi in Ubuntu 22.04  from QBDI-0.10.0-ubuntu22.04-X86_64.deb.
Copy the code from  https://qbdi.readthedocs.io/en/stable/get_started-c.html#full-example
The code in src/test_qbdi.c
I ```cd src``` and  run   ```gcc test_qbdi.c -o test```  in terminal.
Following is the error 
```
gcc test_qbdi.c -o test 
/usr/bin/ld: /tmp/ccPzbMTq.o: in function `showInstruction':
test_qbdi.c:(.text+0x6a): undefined reference to `qbdi_getInstAnalysis'
/usr/bin/ld: /tmp/ccPzbMTq.o: in function `main':
test_qbdi.c:(.text+0x10e): undefined reference to `qbdi_initVM'
/usr/bin/ld: test_qbdi.c:(.text+0x11a): undefined reference to `qbdi_getGPRState'
/usr/bin/ld: test_qbdi.c:(.text+0x166): undefined reference to `qbdi_allocateVirtualStack'
/usr/bin/ld: test_qbdi.c:(.text+0x189): undefined reference to `qbdi_addCodeCB'
/usr/bin/ld: test_qbdi.c:(.text+0x1e9): undefined reference to `qbdi_addMnemonicCB'
/usr/bin/ld: test_qbdi.c:(.text+0x1ff): undefined reference to `qbdi_addInstrumentedModuleFromAddr'
/usr/bin/ld: test_qbdi.c:(.text+0x270): undefined reference to `qbdi_call'
/usr/bin/ld: test_qbdi.c:(.text+0x2cd): undefined reference to `qbdi_alignedFree'
/usr/bin/ld: test_qbdi.c:(.text+0x2d9): undefined reference to `qbdi_terminateVM'
collect2: error: ld returned 1 exit status
```

**Comment by nsurbay** [comment]
Hello,

In order to compile the project, you must link with the shared library QBDI. You should add the option ``-l`` followed the name of the library in order to tell the linker to link against which library you want to link.

If you have no knowledge in compilation, you should use the cmake template (as describe in the [last part of the exemple](https://qbdi.readthedocs.io/en/stable/get_started-c.html#generate-a-template)). CMake will take care of the compiler option.

```
mkdir new_project && cd new_project
qbdi-template
mkdir build && cd build
cmake ..
make
```

**Comment by nsurbay** [comment]
With no update, I will closed this issue. If you have any new issue, feel free to open an new issue.
