### ISSUE TITLE
Frida/QBDI error in macos:Error: access violation accessing 

### ISSUE THREAD

**Issue by immune53** [QBDI/QBDI#260]
**Bug description**

When I use the demo under the qbdi_frida_template directory for testing,
Error: access violation accessing 0x0
    at _call (frida-qbdi.js:1803)
    at apply (native)
    at call (frida-qbdi.js:1809)
    at <anonymous> (FridaQBDI_sample.js:45)

My source code is the code below qbdi_frida_template, and it was generated following the steps in the document.The test program is also compiled from SimpleXOR.c.

**Version :**
- OS: macos14.2
- Architecture: arm64
- QBDI version: latest
- Frida version 16.3.1

**Comment by HoangREALER** [comment]
I also experienced the same problem.

- OS: macOS 14.5
- QBDI version: latest
- Frida version 16.3.3

**Comment by HoangREALER** [comment]
Kinda weird solution to the problem. I duplicated the argument many times for it to work.

```js
vm.call(funcPtr, [strP, strP, strP, strP, strP, strP, strP, strP, strP, strP, strP]);
```

The problem is with the `frida-qbdi.js` file which has a snippet where we need multiple arguments, otherwise the pointers would be 0x0. Maybe there are other more elegant ways to fix this issue.

```js
var _call = function (a, b, c, d, e, f, g, h, i, j) { 
    var retPtr = Memory.alloc(Process.pointerSize);
    var res = QBDI_C.call(vm, retPtr, address, fargs[0], a, b, c, d, e, f, g, h, i, j);
     if (res == false) {
          throw new EvalError('Execution failed');
    }
    return ptr(Memory.readRword(retPtr));
}
```

**Comment by nsurbay** [comment]
Hello,

I just update a mac today (to 14.5) and will try to debug it tomorrow. I never try to use frida on macOS (usually, we use frida with android and we never have this issue).

I don't know exactly why this structure was needed, but if this is the problem, we may change from ``QBDI_C.call`` to ``QBDI_C.callA`` (see [qbdi_callA](https://github.com/QBDI/QBDI/blob/dev-next/include/QBDI/VM_C.h#L198))

**Comment by nsurbay** [comment]
I try to debug, and the problem seems to be an incompatibility in the convention call between the real declaration of ``qbdi_call`` and the call perform in JS. When I dump the argument in JS, all arguments are the expected one, but when I perform the same dump in ``qbdi_call``, the first four variadics argument are missing. ARM64 convention call passes 8 parameters in registers, then the remaining ones on the stack. However, only for macOS, the convention call expects the variadics parameters to always be puts on the stack ([src](https://developer.apple.com/documentation/apple-silicon/addressing-architectural-differences-in-your-macos-code#Dont-Redeclare-a-Function-to-Have-Variable-Parameters)).

The solution is to change the binding definition of QBDI C API. (see #266)

**Comment by HoangREALER** [comment]
I see. Thanks for the help. Much appreciation.

**Comment by nsurbay** [comment]
This seems to be solve the problem. If you have any new issue, feel free to open an new issue.
