### ISSUE TITLE
STOSx instructions not registered as memory accesses

### ISSUE THREAD

**Issue by 0xAcid** [QBDI/QBDI#44]
While playing with **QBDI**, we encountered a bug with the instruction **STOS** (https://www.felixcloutier.com/x86/STOS:STOSB:STOSW:STOSD:STOSQ.html).
It should triggers **memory callbacks** but it does not.

Instrumenting the following code can reproduce the error
```
int blah(int * ptr) {
    asm("stosq");
    return 1;
}
```

We tried to fix it and add the instruction to the **WRITE_64**[] list under s**rc/Patch/X86_64/InstInfo_X86_64.cpp** but it does not work out of the box. We got the following error : 

_[GetWriteAddress::generate] Assertion Failed : false && "No memory address found in the instruction"_

**Comment by haxelion** [comment]
As discussed internally, the real problem is with `REP* [LOD|STO]*` instructions family.
The solution is to have a patch that would emulate the repeat operation by replacing these instructions with the following pseudo-code:

 ```
[LOD|STO]* // Original instruction without the REP prefix
PC <- COND ? INST_ADDRESS : NEXT_ADDRESS // Where COND is the condition of the REP prefix
JMPEpilogue
```

This way the REP is emulated by an engine loop and the original instruction can be safely instrumented to report the memory accesses.
